<?php

namespace App\Service;

class AIGeneratorService
{

    public function __construct()
    {
    }

    public function generateTrainingDescription(string $title, string $category, string $tone = 'professional'): string
    {
        $prompt = $this->buildPrompt($title, $category, $tone);
        
        try {
            // Use curl directly to bypass SSL verification issues
            $ch = curl_init();
            
            // Try direct API with a simpler model first
            $data = [
                'inputs' => $prompt,
                'parameters' => [
                    'max_length' => 1024,
                    'temperature' => 0.7
                ]
            ];
            
            curl_setopt_array($ch, [
                CURLOPT_URL => 'https://api-inference.huggingface.co/models/distilbert-base-uncased',
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_POST => true,
                CURLOPT_POSTFIELDS => json_encode($data),
                CURLOPT_HTTPHEADER => [
                    'Content-Type: application/json',
                    'Authorization: Bearer ' . $this->huggingFaceApiKey
                ],
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_SSL_VERIFYHOST => false,
                CURLOPT_TIMEOUT => 30,
                CURLOPT_VERBOSE => true
            ]);
            
            // Capture verbose output for debugging
            $verbose = fopen('php://temp', 'w+');
            curl_setopt($ch, CURLOPT_STDERR, $verbose);
            
            $response = curl_exec($ch);
            $error = curl_error($ch);
            $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            
            if ($error) {
                throw new \RuntimeException('cURL error: ' . $error);
            }
            
            if ($httpCode !== 200) {
                throw new \RuntimeException('HTTP error: ' . $httpCode . ' Response: ' . $response);
            }
            
            curl_close($ch);
            
            // Log verbose output for debugging
            rewind($verbose);
            $verboseLog = stream_get_contents($verbose);
            fclose($verbose);
            
            // Log the verbose output to error log for debugging
            error_log('Hugging Face API verbose output: ' . $verboseLog);
            error_log('Hugging Face API response: ' . $response);
            
            $content = json_decode($response, true);
            if (json_last_error() !== JSON_ERROR_NONE) {
                throw new \RuntimeException('JSON decode error: ' . json_last_error_msg());
            }
            
            // Handle direct API response format
            if (isset($content[0]['generated_text'])) {
                return $content[0]['generated_text'];
            }
            
            // Handle chat completion format (fallback)
            if (isset($content['choices'][0]['message']['content'])) {
                return $content['choices'][0]['message']['content'];
            }

            throw new \RuntimeException('No content generated by AI. Response: ' . $response);

        } catch (\Exception $e) {
            // Fallback to template-based description when AI fails
            return $this->generateFallbackDescription($title, $category);
        }
    }

    public function generateCoverLetter(string $subject, string $category): string
    {
        $prompt = $this->buildCoverLetterPrompt($subject, $category);
        
        try {
            // Use curl directly to bypass SSL verification issues
            $ch = curl_init();
            
            // Try direct API with a simpler model first
            $data = [
                'inputs' => $prompt,
                'parameters' => [
                    'max_length' => 1024,
                    'temperature' => 0.7
                ]
            ];
            
            curl_setopt_array($ch, [
                CURLOPT_URL => 'https://api-inference.huggingface.co/models/distilbert-base-uncased',
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_POST => true,
                CURLOPT_POSTFIELDS => json_encode($data),
                CURLOPT_HTTPHEADER => [
                    'Content-Type: application/json'
                ],
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_SSL_VERIFYHOST => false,
                CURLOPT_TIMEOUT => 30,
                CURLOPT_VERBOSE => true
            ]);
            
            // Capture verbose output for debugging
            $verbose = fopen('php://temp', 'w+');
            curl_setopt($ch, CURLOPT_STDERR, $verbose);
            
            $response = curl_exec($ch);
            $error = curl_error($ch);
            $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            
            if ($error) {
                throw new \RuntimeException('cURL error: ' . $error);
            }
            
            if ($httpCode !== 200) {
                throw new \RuntimeException('HTTP error: ' . $httpCode . ' Response: ' . $response);
            }
            
            curl_close($ch);
            
            // Log verbose output for debugging
            rewind($verbose);
            $verboseLog = stream_get_contents($verbose);
            fclose($verbose);
            
            // Log the verbose output to error log for debugging
            error_log('Hugging Face API verbose output: ' . $verboseLog);
            error_log('Hugging Face API response: ' . $response);
            
            $content = json_decode($response, true);
            if (json_last_error() !== JSON_ERROR_NONE) {
                throw new \RuntimeException('JSON decode error: ' . json_last_error_msg());
            }
            
            // Handle direct API response format
            if (isset($content[0]['generated_text'])) {
                return $content[0]['generated_text'];
            }
            
            // Handle chat completion format (fallback)
            if (isset($content['choices'][0]['message']['content'])) {
                return $content['choices'][0]['message']['content'];
            }

            throw new \RuntimeException('No content generated by AI. Response: ' . $response);

        } catch (\Exception $e) {
            // Fallback to template-based cover letter when AI fails
            return $this->generateFallbackCoverLetter($subject, $category);
        }
    }

    private function buildCoverLetterPrompt(string $subject, string $category): string
    {
        return "Generate a professional cover letter for a spontaneous job application with the following details:

Subject/Job Title: {$subject}
Category: {$category}

Please create a compelling cover letter that includes:
1. Professional greeting and introduction
2. Explanation of why the candidate is interested in this type of opportunity
3. Relevant skills and experience related to the {$category} field
4. Career objectives and what the candidate hopes to achieve
5. Professional closing with call to action

The cover letter should be:
- Professional and engaging
- 250-400 words in length
- Written in a formal but approachable tone
- Specific to the {$category} industry/field
- Suitable for a spontaneous application (no specific job posting)

Make it sound enthusiastic and professional, highlighting the candidate's potential value to the company.";
    }

    private function generateFallbackDescription(string $title, string $category, string $tone = 'professional'): string
    {
        // Generate truly unique content using dynamic elements and tone
        $learningObjectives = $this->generateLearningObjectives($category);
        $targetAudience = $this->generateTargetAudience($category);
        $keyTopics = $this->generateKeyTopics($title, $category);
        $outcomes = $this->generateOutcomes($category);
        $duration = $this->generateDuration();
        $deliveryMethod = $this->generateDeliveryMethod();
        $toneStyle = $this->getToneInstructions($tone);
        
        $descriptions = [
            'IT' => $this->generateITDescription($title, $category, $tone, $duration, $deliveryMethod, $learningObjectives, $targetAudience, $keyTopics, $outcomes),
            
            'Marketing' => $this->generateMarketingDescription($title, $category, $tone, $duration, $deliveryMethod, $learningObjectives, $targetAudience, $keyTopics, $outcomes),
            
            'Sales' => $this->generateSalesDescription($title, $category, $tone, $duration, $deliveryMethod, $learningObjectives, $targetAudience, $keyTopics, $outcomes),
            
            'HR' => "This comprehensive {$title} training program develops HR professionals into strategic partners who drive organizational success through effective people management and talent development.

Over {$duration}, participants engage with {$keyTopics} through {$deliveryMethod} sessions that combine HR theory with practical application. Experienced HR leaders share insights on strategic workforce planning, employee engagement, and creating cultures that attract and retain top talent.

Strategic focus areas:
{$learningObjectives}

This program serves {$targetAudience} who want to advance from administrative HR to strategic leadership roles. The curriculum addresses current challenges like remote workforce management, diversity and inclusion, and data-driven HR decision-making.

Participants will develop:
{$outcomes}

Graduates will be equipped to design and implement HR strategies that align with business objectives, foster organizational excellence, and create workplaces where talent thrives and business goals are achieved.",
            
            'Finance' => "This advanced {$title} training program provides finance professionals with sophisticated analytical skills and strategic insights needed to excel in today's complex financial environment.

During {$duration}, participants master {$keyTopics} through {$deliveryMethod} learning experiences that blend financial theory with practical application. Industry experts share cutting-edge techniques in financial analysis, risk management, and strategic decision-making.

Essential skills developed:
{$learningObjectives}

Designed for {$targetAudience}, this program addresses the full spectrum of financial operations from tactical execution to strategic planning. Participants learn to leverage technology, data analytics, and emerging financial models to drive business value.

Participants will acquire:
{$outcomes}

Graduates will possess the financial acumen and strategic thinking needed to optimize resource allocation, manage risk effectively, and provide financial leadership that drives organizational growth and profitability.",
            
            'Leadership' => "This transformative {$title} training program develops exceptional leaders who inspire teams, drive change, and achieve extraordinary results in today's dynamic business environment.

Through {$duration} of {$deliveryMethod} development, participants explore {$keyTopics} using proven leadership frameworks and real-world case studies. Seasoned executives share insights on strategic vision, emotional intelligence, and creating cultures of excellence and innovation.

Leadership competencies:
{$learningObjectives}

This program is designed for {$targetAudience} who want to elevate their leadership impact and organizational influence. The curriculum addresses modern leadership challenges including remote team management, change acceleration, and fostering inclusive environments.

Participants will develop:
{$outcomes}
Project management excellence:
{$learningObjectives}

Designed for {$targetAudience}, this program covers both traditional and agile approaches, preparing participants to manage projects of any size and complexity. The curriculum addresses current challenges like remote team coordination and digital project delivery.

Participants will develop:
{$outcomes}

Graduates will be equipped to lead projects successfully, manage risks effectively, and deliver strategic value through exceptional project execution and stakeholder management.",
            
            'General' => "This engaging {$title} training program delivers valuable knowledge and practical skills that participants can immediately apply to enhance their professional performance and career advancement.

Over {$duration}, learners explore {$keyTopics} through {$deliveryMethod} experiences that balance theoretical understanding with hands-on application. Industry experts share current best practices, emerging trends, and proven techniques that deliver workplace value.

Key development areas:
{$learningObjectives}

Perfect for {$targetAudience}, this program adapts to various experience levels and learning styles. Participants gain both foundational knowledge and advanced techniques that can be applied immediately in their professional roles.

Participants will develop:
{$outcomes}

Upon completion, graduates will have the confidence, skills, and insights needed to excel in their current roles while positioning themselves for future career opportunities and professional growth."
        ];
        
        $template = $descriptions[$category] ?? $descriptions['General'];
        return str_replace('{$title}', $title, $template);
    }

    private function generateLearningObjectives(string $category): string
    {
        $objectives = [
            'IT' => "- Mastering modern programming languages and frameworks\n- Developing problem-solving and debugging skills\n- Understanding system architecture and design patterns\n- Implementing security best practices and protocols\n- Creating scalable and maintainable code solutions",
            
            'Marketing' => "- Developing data-driven marketing strategies\n- Mastering digital marketing channels and tools\n- Creating compelling content and brand messaging\n- Analyzing market trends and consumer behavior\n- Implementing effective campaign measurement and optimization",
            'Sales' => "- Building consultative selling and relationship skills\n- Mastering negotiation and closing techniques\n- Understanding customer needs and value proposition\n- Developing territory management and prospecting strategies\n- Creating effective sales presentations and proposals",
            
            'HR' => "- Designing strategic workforce planning initiatives\n- Implementing talent acquisition and retention programs\n- Developing performance management systems\n- Creating employee engagement and development programs\n- Understanding labor law compliance and risk management",
            
            'Finance' => "- Mastering financial analysis and reporting techniques\n- Developing budget planning and forecasting skills\n- Understanding investment and portfolio management\n- Implementing risk assessment and mitigation strategies\n- Creating financial models and business valuation frameworks",
            
            'Leadership' => "- Developing strategic vision and decision-making capabilities\n- Building effective team leadership and motivation skills\n- Mastering change management and organizational transformation\n- Creating inclusive and high-performance cultures\n- Understanding stakeholder management and communication",
            
            'Communication' => "- Developing persuasive verbal and written communication\n- Mastering presentation and public speaking skills\n- Understanding cross-cultural and remote communication\n- Creating effective digital and social media communication\n- Building interpersonal and relationship management skills",
            
            'Project Management' => "- Mastering project planning and scheduling methodologies\n- Developing risk management and mitigation strategies\n- Understanding resource allocation and budget management\n- Building team leadership and stakeholder communication\n- Implementing agile and waterfall project frameworks",
            
            'General' => "- Developing critical thinking and problem-solving abilities\n- Building effective collaboration and teamwork skills\n- Mastering time management and productivity techniques\n- Creating professional communication and presentation skills\n- Understanding industry best practices and standards"
        ];
        
        return $objectives[$category] ?? $objectives['General'];
    }

    private function generateTargetAudience(string $category): string
    {
        $audiences = [
            'IT' => "software developers, system administrators, IT professionals, and technology enthusiasts seeking to enhance their technical expertise",
            'Marketing' => "marketing professionals, brand managers, digital marketers, and business owners looking to strengthen their marketing capabilities",
            'Sales' => "sales representatives, account managers, business development professionals, and sales leaders aiming to improve their performance",
            'HR' => "HR specialists, talent acquisition professionals, HR managers, and business leaders responsible for people management",
            'Finance' => "financial analysts, accountants, finance managers, and business professionals seeking to enhance their financial acumen",
            'Leadership' => "team leaders, department managers, executives, and professionals aspiring to leadership roles",
            'Communication' => "professionals at all levels seeking to improve their communication effectiveness and influence",
            'Project Management' => "project managers, team leads, coordinators, and professionals responsible for project delivery",
            'General' => "professionals across all industries seeking to enhance their skills and advance their careers"
        ];
        
        return $audiences[$category] ?? $audiences['General'];
    }

    private function generateKeyTopics(string $title, string $category): string
    {
        $topics = [
            'IT' => "advanced programming concepts, system design, cloud architecture, cybersecurity protocols, and emerging technologies",
            'Marketing' => "digital marketing strategies, content creation, data analytics, customer journey mapping, and brand development",
            'Sales' => "consultative selling techniques, negotiation strategies, customer relationship management, and sales analytics",
            'HR' => "strategic workforce planning, talent development, performance management, employee engagement, and organizational design",
            'Finance' => "financial modeling, investment analysis, risk management, budget optimization, and regulatory compliance",
            'Leadership' => "strategic thinking, emotional intelligence, change management, team development, and organizational culture",
            'Communication' => "interpersonal communication, presentation skills, digital communication, cross-cultural competence, and conflict resolution",
            'Project Management' => "project lifecycle management, risk assessment, resource planning, stakeholder management, and quality assurance",
            'General' => "industry-specific best practices, professional development, skill enhancement, and career advancement strategies"
        ];
        
        return $topics[$category] ?? $topics['General'];
    }

    private function generateOutcomes(string $category): string
    {
        $outcomes = [
            'IT' => "advanced technical proficiency, innovative problem-solving abilities, and the capacity to design and implement complex technological solutions",
            'Marketing' => "strategic marketing expertise, data-driven decision-making capabilities, and the skills to create impactful marketing campaigns",
            'Sales' => "enhanced selling capabilities, stronger customer relationships, and the ability to consistently achieve and exceed sales targets",
            'HR' => "strategic HR leadership, talent management expertise, and the ability to drive organizational success through people initiatives",
            'Finance' => "advanced financial analysis skills, strategic financial planning capabilities, and the expertise to optimize financial performance",
            'Leadership' => "transformative leadership abilities, strategic vision, and the capacity to inspire and guide teams to exceptional performance",
            'Communication' => "masterful communication skills, persuasive abilities, and the confidence to effectively communicate in any professional context",
            'Project Management' => "comprehensive project management expertise, risk management capabilities, and the skills to deliver successful projects",
            'General' => "enhanced professional capabilities, improved performance, and the foundation for continued career growth and success"
        ];
        
        return $outcomes[$category] ?? $outcomes['General'];
    }

    private function generateDuration(): string
    {
        $durations = ['2 weeks', '3 weeks', '4 weeks', '6 weeks', '8 weeks', '10 weeks', '12 weeks'];
        return $durations[array_rand($durations)];
    }

    private function generateDeliveryMethod(): string
    {
        $methods = ['interactive', 'hands-on', 'experiential', 'blended learning', 'practical', 'workshop-style', 'case study-based'];
        return $methods[array_rand($methods)];
    }

    private function generateITDescription(string $title, string $category, string $tone, string $duration, string $deliveryMethod, string $learningObjectives, string $targetAudience, string $keyTopics, string $outcomes): string
    {
        $toneContent = $this->getToneContent($tone, $category);
        
        return "This {$toneContent['intensity']} {$title} training program {$toneContent['action']} cutting-edge technical expertise essential for today's digital transformation landscape.

Over {$duration}, participants will master {$keyTopics} through {$deliveryMethod} sessions that combine theoretical foundations with hands-on implementation. Our expert instructors guide learners through real-world scenarios, industry-standard tools, and best practices that align with current market demands.

{$toneContent['learning']}

The curriculum is specifically designed for {$targetAudience} who want to advance their technical careers or transition into specialized roles. Each module builds upon previous knowledge, creating a comprehensive learning path that ensures mastery of complex concepts.

Participants will develop:
{$outcomes}

By program completion, graduates will possess the technical proficiency and problem-solving capabilities needed to drive innovation and excellence in their organizations' technology initiatives.";
    }

    private function generateMarketingDescription(string $title, string $category, string $tone, string $duration, string $deliveryMethod, string $learningObjectives, string $targetAudience, string $keyTopics, string $outcomes): string
    {
        $toneContent = $this->getToneContent($tone, $category);
        
        return "This strategic {$title} training program {$toneContent['action']} marketing professionals with advanced techniques and methodologies that drive measurable business results in today's competitive marketplace.

During {$duration}, participants will explore {$keyTopics} through {$deliveryMethod} learning experiences that blend strategic thinking with practical application. Industry experts share insights on emerging trends, digital transformation, and proven frameworks that deliver exceptional marketing outcomes.

{$toneContent['learning']}

This program is ideal for {$targetAudience} seeking to elevate their marketing expertise and leadership capabilities. The curriculum addresses current challenges and opportunities in marketing landscape, ensuring participants can immediately apply learned concepts.

Participants will develop:
{$outcomes}

Graduates will emerge with strategic vision and tactical skills needed to create impactful marketing campaigns, optimize performance metrics, and lead successful marketing initiatives in any organization.";
    }

    private function generateSalesDescription(string $title, string $category, string $tone, string $duration, string $deliveryMethod, string $learningObjectives, string $targetAudience, string $keyTopics, string $outcomes): string
    {
        $toneContent = $this->getToneContent($tone, $category);
        
        return "This results-oriented {$title} training program {$toneContent['action']} sales professionals into high-performing experts who consistently exceed targets and build lasting customer relationships.

Through {$duration} of {$deliveryMethod} training, participants master {$keyTopics} using proven methodologies and cutting-edge sales techniques. Our veteran sales trainers share battle-tested strategies, psychological insights, and practical tools that drive immediate performance improvements.

{$toneContent['learning']}

Designed for {$targetAudience}, this program addresses the full sales cycle from prospecting to closing, with emphasis on building value-based relationships and consultative selling approaches. Participants learn to adapt their style to different customer personas and market conditions.

Participants will gain:
{$outcomes}

Upon completion, sales professionals will have the confidence, skills, and strategic mindset needed to consistently achieve quota, expand market share, and become trusted advisors to their clients.";
    }

    private function generateHRDescription(string $title, string $category, string $tone, string $duration, string $deliveryMethod, string $learningObjectives, string $targetAudience, string $keyTopics, string $outcomes): string
    {
        $toneContent = $this->getToneContent($tone, $category);
        
        return "This comprehensive {$title} training program {$toneContent['action']} HR professionals into strategic partners who drive organizational success through effective people management and talent development.

Over {$duration}, participants engage with {$keyTopics} through {$deliveryMethod} sessions that combine HR theory with practical application. Experienced HR leaders share insights on strategic workforce planning, employee engagement, and creating cultures that attract and retain top talent.

{$toneContent['learning']}

This program serves {$targetAudience} who want to advance from administrative HR to strategic leadership roles. The curriculum addresses current challenges like remote workforce management, diversity and inclusion, and data-driven HR decision-making.

Participants will develop:
{$outcomes}

Graduates will be equipped to design and implement HR strategies that align with business objectives, foster organizational excellence, and create workplaces where talent thrives and business goals are achieved.";
    }

    private function generateFinanceDescription(string $title, string $category, string $tone, string $duration, string $deliveryMethod, string $learningObjectives, string $targetAudience, string $keyTopics, string $outcomes): string
    {
        $toneContent = $this->getToneContent($tone, $category);
        
        return "This advanced {$title} training program {$toneContent['action']} finance professionals with sophisticated analytical skills and strategic insights needed for success in today's complex financial environment.

During {$duration}, participants master {$keyTopics} through {$deliveryMethod} learning experiences that blend financial theory with practical application. Industry experts share cutting-edge techniques in financial analysis, risk management, and strategic decision-making.

{$toneContent['learning']}

Designed for {$targetAudience}, this program addresses the full spectrum of financial operations from tactical execution to strategic planning. Participants learn to leverage technology, data analytics, and emerging financial models to drive business value.

Participants will develop:
{$outcomes}

Graduates will possess the financial acumen and strategic thinking needed to optimize resource allocation, manage risk effectively, and provide financial leadership that drives organizational growth and profitability.";
    }

    private function generateLeadershipDescription(string $title, string $category, string $tone, string $duration, string $deliveryMethod, string $learningObjectives, string $targetAudience, string $keyTopics, string $outcomes): string
    {
        $toneContent = $this->getToneContent($tone, $category);
        
        return "This transformable {$title} training program {$toneContent['action']} exceptional leaders who inspire teams, drive change, and achieve extraordinary results in today's dynamic business environment.

Through {$duration} of {$deliveryMethod} development, participants explore {$keyTopics} using proven leadership frameworks and real-world case studies. Seasoned executives share insights on strategic vision, emotional intelligence, and creating cultures of excellence and innovation.

{$toneContent['learning']}

This program is designed for {$targetAudience} who want to elevate their leadership impact and organizational influence. The curriculum addresses modern leadership challenges including remote team management, change acceleration, and fostering inclusive environments.

Participants will develop:
{$outcomes}

Graduates emerge with leadership presence, strategic mindset, and people skills needed to build high-performing teams, drive organizational transformation, and create lasting positive impact.";
    }

    private function generateCommunicationDescription(string $title, string $category, string $tone, string $duration, string $deliveryMethod, string $learningObjectives, string $targetAudience, string $keyTopics, string $outcomes): string
    {
        $toneContent = $this->getToneContent($tone, $category);
        
        return "This dynamic {$title} training program {$toneContent['action']} professionals into masterful communicators who can influence, persuade, and connect effectively in any business context.

Over {$duration}, participants develop expertise in {$keyTopics} through {$deliveryMethod} practice sessions, feedback loops, and real-world applications. Communication experts guide participants through proven techniques, current best practices, and emerging trends in business communication.

{$toneContent['learning']}

Ideal for {$targetAudience}, this program addresses all aspects of professional communication from interpersonal skills to executive presentations. Participants learn to adapt their communication style to different audiences, cultures, and situations.

Participants will gain:
{$outcomes}

Graduates possess the communication confidence and versatility needed to build relationships, influence decisions, and advance their careers through exceptional communication capabilities.";
    }

    private function generateProjectManagementDescription(string $title, string $category, string $tone, string $duration, string $deliveryMethod, string $learningObjectives, string $targetAudience, string $keyTopics, string $outcomes): string
    {
        $toneContent = $this->getToneContent($tone, $category);
        
        return "This comprehensive {$title} training program {$toneContent['action']} skilled project managers who deliver projects on time, within budget, and beyond expectations in today's complex business landscape.

During {$duration}, participants master {$keyTopics} through {$deliveryMethod} learning that combines PM methodologies with practical application. Certified project managers share insights on agile transformation, stakeholder management, and leveraging technology for project success.

{$toneContent['learning']}

Designed for {$targetAudience}, this program covers both traditional and agile approaches, preparing participants to manage projects of any size and complexity. The curriculum addresses current challenges like remote team coordination and digital project delivery.

Participants will develop:
{$outcomes}

Graduates will be equipped to lead projects successfully, manage risks effectively, and deliver strategic value through exceptional project execution and stakeholder management.";
    }

    private function generateGeneralDescription(string $title, string $category, string $tone, string $duration, string $deliveryMethod, string $learningObjectives, string $targetAudience, string $keyTopics, string $outcomes): string
    {
        $toneContent = $this->getToneContent($tone, $category);
        
        return "This engaging {$title} training program {$toneContent['action']} participants with valuable knowledge and practical skills that can be immediately applied in their professional roles.

Over {$duration}, learners explore {$keyTopics} through {$deliveryMethod} experiences that balance theoretical understanding with hands-on application. Industry experts share current best practices, emerging trends, and practical techniques that deliver workplace value.

{$toneContent['learning']}

Perfect for {$targetAudience}, this program adapts to various learning styles and focuses on practical applications that deliver immediate workplace benefits. Participants gain both foundational knowledge and advanced techniques that can be applied immediately.

Participants will develop:
{$outcomes}

Upon completion, graduates will have the expertise, confidence, and tools needed to excel in their current roles while positioning themselves for future career opportunities and professional growth.";
    }

    private function getToneContent(string $tone, string $category): array
    {
        $tonePatterns = [
            'professional' => ['intensity' => 'intensive', 'action' => 'delivers', 'learning' => 'Learning objectives focus on:'],
            'formal' => ['intensity' => 'comprehensive', 'action' => 'provides', 'learning' => 'Educational components include:'],
            'friendly' => ['intensity' => 'engaging', 'action' => 'offers', 'learning' => 'Key learning areas:'],
            'casual' => ['intensity' => 'relaxed', 'action' => 'covers', 'learning' => 'Main topics include:'],
            'funny' => ['intensity' => 'entertaining', 'action' => 'makes', 'learning' => 'Fun learning points:'],
            'creative' => ['intensity' => 'innovative', 'action' => 'sparks', 'learning' => 'Creative elements:'],
            'technical' => ['intensity' => 'detailed', 'action' => 'covers', 'learning' => 'Technical modules:'],
            'inspirational' => ['intensity' => 'transformative', 'action' => 'empowers', 'learning' => 'Growth opportunities:'],
            'persuasive' => ['intensity' => 'compelling', 'action' => 'demonstrates', 'learning' => 'Value propositions:']
        ];
        
        return $tonePatterns[$tone] ?? $tonePatterns['professional'];
    }

    public function generateSuggestedSalary(string $jobTitle, string $location): string
    {
        $prompt = "Based on the job title '{$jobTitle}' in '{$location}', suggest an appropriate annual salary range. Consider factors like experience level required, industry standards, and local market conditions. Provide the salary as a specific range (e.g., '$45,000 - $65,000') or a single representative figure (e.g., '$55,000').";

        try {
            // Use curl directly to bypass SSL verification issues
            $ch = curl_init();
            
            $data = [
                'model' => 'adzuna-llama-2-7b-chat',
                'messages' => [
                    [
                        'role' => 'user',
                        'content' => $prompt
                    ]
                ],
                'max_tokens' => 150,
                'temperature' => 0.3
            ];
            
            curl_setopt_array($ch, [
                CURLOPT_URL => 'https://api.adzuna.com/v1/chat/completions',
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_POST => true,
                CURLOPT_POSTFIELDS => json_encode($data),
                CURLOPT_HTTPHEADER => [
                    'Content-Type: application/json'
                ],
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_SSL_VERIFYHOST => false,
                CURLOPT_TIMEOUT => 30,
                CURLOPT_VERBOSE => true
            ]);
            
            $response = curl_exec($ch);
            $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            curl_close($ch);
            
            if ($response === false) {
                return $this->generateFallbackSalary($jobTitle, $location);
            }
            
            $result = json_decode($response, true);
            
            if ($httpCode !== 200 || !isset($result['choices'][0]['message']['content'])) {
                return $this->generateFallbackSalary($jobTitle, $location);
            }
            
            $suggestedSalary = $result['choices'][0]['message']['content'];
            
            // Clean up the response to get just the salary figure
            if (preg_match('/\$?([0-9,]+(?:\s*-\s*[0-9,]+)?\s*\$?/', $suggestedSalary, $matches)) {
                return $matches[1];
            }
            
            return $suggestedSalary;
            
        } catch (\Exception $e) {
            return $this->generateFallbackSalary($jobTitle, $location);
        }
    }

    private function generateFallbackSalary(string $jobTitle, string $location): string
    {
        $salaryRanges = [
            'IT/Software' => [
                'Junior Developer' => '$45,000 - $65,000',
                'Senior Developer' => '$75,000 - $95,000',
                'Tech Lead' => '$85,000 - $120,000'
            ],
            'Marketing' => [
                'Marketing Coordinator' => '$40,000 - $55,000',
                'Marketing Manager' => '$60,000 - $80,000',
                'Digital Marketing Specialist' => '$50,000 - $70,000'
            ],
            'Sales' => [
                'Sales Representative' => '$35,000 - $50,000',
                'Sales Manager' => '$55,000 - $75,000',
                'Account Executive' => '$65,000 - $90,000'
            ],
            'HR' => [
                'HR Coordinator' => '$45,000 - $60,000',
                'HR Manager' => '$60,000 - $80,000',
                'HR Director' => '$80,000 - $100,000'
            ],
            'Finance' => [
                'Financial Analyst' => '$55,000 - $75,000',
                'Finance Manager' => '$70,000 - $90,000',
                'CFO' => '$100,000 - $150,000'
            ]
        ];

        // Try to match job title to a category and level
        $category = $this->categorizeJobTitle($jobTitle);
        $level = $this->detectExperienceLevel($jobTitle);
        
        if (isset($salaryRanges[$category][$level])) {
            return $salaryRanges[$category][$level];
        }
        
        // Fallback to general ranges
        $generalRanges = [
            'Entry Level' => '$35,000 - $50,000',
            'Mid Level' => '$50,000 - $75,000',
            'Senior Level' => '$75,000 - $100,000'
        ];
        
        return $generalRanges[$level] ?? '$50,000 - $70,000';
    }

    private function categorizeJobTitle(string $jobTitle): string
    {
        $keywords = [
            'IT/Software' => ['developer', 'programmer', 'software', 'engineer', 'technical', 'IT'],
            'Marketing' => ['marketing', 'digital', 'social media', 'brand', 'advertising'],
            'Sales' => ['sales', 'business development', 'account', 'revenue'],
            'HR' => ['human resources', 'HR', 'recruiting', 'personnel'],
            'Finance' => ['finance', 'financial', 'accounting', 'analyst', 'investment']
        ];

        foreach ($keywords as $category => $words) {
            foreach ($words as $word) {
                if (stripos(strtolower($jobTitle), $word) !== false) {
                    return $category;
                }
            }
        }
        
        return 'General';
    }

    private function detectExperienceLevel(string $jobTitle): string
    {
        $seniorKeywords = ['senior', 'lead', 'manager', 'director', 'head', 'principal', 'chief'];
        $juniorKeywords = ['junior', 'entry', 'associate', 'assistant', 'coordinator'];
        
        $title = strtolower($jobTitle);
        
        foreach ($seniorKeywords as $keyword) {
            if (stripos($title, $keyword) !== false) {
                return 'Senior Level';
            }
        }
        
        foreach ($juniorKeywords as $keyword) {
            if (stripos($title, $keyword) !== false) {
                return 'Entry Level';
            }
        }
        
        return 'Mid Level';
    }

    public function generateEditingTips(string $title, string $category, string $description, string $tone = 'professional'): array
    {
        $prompt = $this->buildEditingTipsPrompt($title, $category, $description, $tone);
        
        try {
            // Use curl directly to bypass SSL verification issues
            $ch = curl_init();
            
            // Try direct API with a simpler model first
            $data = [
                'inputs' => $prompt,
                'parameters' => [
                    'max_length' => 512,
                    'temperature' => 0.7
                ]
            ];
            
            curl_setopt_array($ch, [
                CURLOPT_URL => 'https://api-inference.huggingface.co/models/distilbert-base-uncased',
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_POST => true,
                CURLOPT_POSTFIELDS => json_encode($data),
                CURLOPT_HTTPHEADER => [
                    'Content-Type: application/json'
                ],
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_SSL_VERIFYHOST => false,
                CURLOPT_TIMEOUT => 30,
                CURLOPT_VERBOSE => true
            ]);
            
            $response = curl_exec($ch);
            $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            curl_close($ch);
            
            if ($response === false) {
                return $this->generateFallbackEditingTips($title, $category, $description, $tone);
            }
            
            $result = json_decode($response, true);
            
            if ($httpCode !== 200 || !isset($result[0]['generated_text'])) {
                return $this->generateFallbackEditingTips($title, $category, $description, $tone);
            }
            
            $aiTips = $result[0]['generated_text'];
            
            // Parse AI response into structured tips
            return $this->parseEditingTips($aiTips, $title, $category, $tone);
            
        } catch (\Exception $e) {
            return $this->generateFallbackEditingTips($title, $category, $description, $tone);
        }
    }

    private function buildEditingTipsPrompt(string $title, string $category, string $description, string $tone): string
    {
        $toneInstructions = $this->getToneInstructions($tone);
        
        return "You are an expert content editor and training specialist. Analyze the following training content and provide 4 specific, actionable editing tips to improve it.

Training Title: {$title}
Category: {$category}
Current Description: {$description}

{$toneInstructions}

Focus on:
1. Content clarity and structure
2. Engagement and readability
3. Technical accuracy and completeness
4. Learning effectiveness and outcomes

Provide your response as a numbered list with each tip being concise (under 20 words) and actionable. Start each tip with a strong action verb.";
    }

    private function parseEditingTips(string $aiTips, string $title, string $category, string $tone): array
    {
        // Try to parse AI response into structured tips
        $lines = explode("\n", $aiTips);
        $tips = [];
        
        foreach ($lines as $line) {
            $line = trim($line);
            
            // Look for numbered items or bullet points
            if (preg_match('/^\d+\.\s*(.+)/', $line, $matches)) {
                $tips[] = trim($matches[1]);
            } elseif (preg_match('/^[•\-\*]\s*(.+)/', $line, $matches)) {
                $tips[] = trim($matches[1]);
            } elseif (!empty($line) && strlen($line) > 5) {
                $tips[] = $line;
            }
        }
        
        // If we couldn't parse AI response, use fallback
        if (count($tips) < 3) {
            return $this->generateFallbackEditingTips($title, $category, $description, $tone);
        }
        
        return [
            'tips' => array_slice($tips, 0, 4),
            'source' => 'ai',
            'confidence' => 'high'
        ];
    }

    private function generateFallbackEditingTips(string $title, string $category, string $description, string $tone): array
    {
        $tipSets = [
            'professional' => [
                'Structure your content with clear headings and bullet points',
                'Include measurable learning objectives and outcomes',
                'Add specific examples and case studies',
                'Ensure technical accuracy and up-to-date information'
            ],
            'formal' => [
                'Use formal academic language throughout',
                'Include comprehensive theoretical frameworks',
                'Add proper citations and references',
                'Maintain consistent professional tone'
            ],
            'friendly' => [
                'Use conversational and encouraging language',
                'Include relatable examples and stories',
                'Add interactive elements and questions',
                'Keep sentences short and easy to read'
            ],
            'casual' => [
                'Write in a relaxed, approachable style',
                'Use everyday language and analogies',
                'Include practical tips and shortcuts',
                'Add humor and personal touches'
            ],
            'technical' => [
                'Include specific technical terminology',
                'Add code examples and technical details',
                'Provide in-depth explanations',
                'Include troubleshooting and common issues'
            ]
        ];
        
        return [
            'tips' => $tipSets[$tone] ?? $tipSets['professional'],
            'source' => 'fallback',
            'confidence' => 'medium'
        ];
    }

    private function generateFallbackCoverLetter(string $subject, string $category): string
    {
        $templates = [
            'IT/Software' => "Dear Hiring Manager,

I am writing to express my interest in opportunities within your organization for a {$subject} position. With my strong background in software development and technology, I am confident in my ability to contribute meaningfully to your team.

My experience includes working with modern technologies and development methodologies that align well with the current demands of the IT industry. I am particularly drawn to your company because of its reputation for innovation and commitment to excellence.

I would welcome the opportunity to discuss how my skills and enthusiasm could benefit your organization. Thank you for considering your application.

Sincerely,
[Your Name]",
            'Marketing' => "Dear Hiring Manager,

I am excited to submit my application for opportunities in the marketing field, specifically for roles related to {$subject}. My background in digital marketing and creative strategy has prepared me to make immediate contributions to your marketing team.

I have experience developing comprehensive marketing campaigns, analyzing market trends, and creating compelling content that drives engagement. Your company's innovative approach to marketing resonates with my professional values and career aspirations.

I look forward to the possibility of discussing how my creativity and analytical skills could support your marketing objectives.

Best regards,
[Your Name]",
            'Sales' => "Dear Hiring Manager,

I am writing to express my strong interest in sales opportunities within your organization, particularly in roles involving {$subject}. My proven track record in sales and customer relationship management makes me confident in my ability to drive results for your team.

I excel at building lasting client relationships, understanding customer needs, and delivering solutions that exceed expectations. Your company's reputation for excellence in sales and customer service aligns perfectly with my professional goals.

I would welcome the opportunity to discuss how my sales expertise and passion for customer success could benefit your organization.

Sincerely,
[Your Name]",
            'Human Resources' => "Dear Hiring Manager,

I am writing to express my interest in HR opportunities within your organization, particularly positions related to {$subject}. My background in human resources and talent management has equipped me with the skills necessary to contribute effectively to your HR team.

I have experience in recruitment, employee relations, and developing HR strategies that support organizational growth. Your company's commitment to creating a positive work environment and investing in employee development aligns with my professional values.

I look forward to discussing how my HR expertise could support your organization's talent management goals.

Best regards,
[Your Name]",
            'General' => "Dear Hiring Manager,

I am writing to express my interest in opportunities within your organization for a {$subject} position. With my professional background and transferable skills, I am confident in my ability to make valuable contributions to your team.

My experience has prepared me to adapt to new challenges and deliver results in dynamic environments. I am particularly drawn to your company because of its reputation for excellence and commitment to professional development.

I would welcome the opportunity to discuss how my skills and enthusiasm could benefit your organization. Thank you for considering my application.

Sincerely,
[Your Name]"
        ];

        $template = $templates[$category] ?? $templates['General'];
        return str_replace('{$subject}', $subject, $template);
    }

    private function buildPrompt(string $title, string $category, string $tone = 'professional'): string
    {
        $toneInstructions = $this->getToneInstructions($tone);
        
        return "Generate a comprehensive training description for the following training:

Title: {$title}
Category: {$category}
Tone: {$tone}

{$toneInstructions}

Please create a detailed description that includes:
1. Training objectives and learning outcomes
2. Target audience and prerequisites
3. Key topics and modules to be covered
4. Skills participants will develop
5. Practical applications and benefits

The description should be between 200-400 words. Format it in clear paragraphs with bullet points for key topics.

Make it specific to the {$category} field and relevant to modern professional development needs.";
    }

    private function getToneInstructions(string $tone): string
    {
        $toneStyles = [
            'professional' => "Write in a professional, formal tone suitable for corporate training environments. Use industry-standard terminology and maintain a knowledgeable, authoritative voice.",
            'formal' => "Write in a very formal, academic tone with sophisticated vocabulary. Use proper business language and maintain a respectful, serious approach.",
            'friendly' => "Write in a warm, approachable tone that feels welcoming and encouraging. Use conversational language while maintaining professionalism.",
            'casual' => "Write in a relaxed, informal tone that feels approachable and easy to understand. Use everyday language and a friendly, conversational style.",
            'funny' => "Write with humor and wit while maintaining professionalism. Include light-hearted elements and amusing observations that make learning enjoyable.",
            'creative' => "Write in an imaginative, innovative tone with vivid descriptions and engaging language. Use metaphors, storytelling elements, and creative expressions.",
            'technical' => "Write with precise technical terminology and detailed explanations. Focus on technical accuracy, specifications, and industry-specific jargon where appropriate.",
            'inspirational' => "Write in an uplifting, motivational tone that inspires and encourages. Use positive language and focus on growth potential.",
            'persuasive' => "Write in a convincing, influential tone that highlights benefits and value. Use compelling language and persuasive techniques."
        ];
        
        return $toneStyles[$tone] ?? $toneStyles['professional'];
    }
}
